from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from score_skill_task import ABILITY_LABELS, score_task, validate_tasks

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TASKS_DIR = ROOT / "examples" / "skill_tasks"
DEFAULT_ANSWERS_DIR = ROOT / "examples" / "skill_task_answers" / "reference"
DEFAULT_OUTPUT = ROOT / "docs" / "results" / "skill_task_matrix.md"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the TradeArena skill task matrix report.")
    parser.add_argument("--tasks-dir", default=str(DEFAULT_TASKS_DIR), help="Directory containing skill task folders.")
    parser.add_argument("--answers-dir", default=str(DEFAULT_ANSWERS_DIR), help="Optional directory of <task_id>.md answers to score.")
    parser.add_argument("--answers-label", default="reference", help="Label for the scored answer set.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Markdown report path.")
    parser.add_argument("--check", action="store_true", help="Fail if the tracked report is stale.")
    args = parser.parse_args(argv)

    tasks_dir = Path(args.tasks_dir)
    output = Path(args.output)
    task_paths = sorted(path for path in tasks_dir.iterdir() if path.is_dir())
    failures = validate_tasks(task_paths)
    if failures:
        print("Skill task matrix validation failed:")
        for failure in failures:
            print(f"  - {failure}")
        return 1

    answers_dir = Path(args.answers_dir)
    answer_scores = score_answers(task_paths, answers_dir) if answers_dir.exists() else []
    markdown = render_report(task_paths, answer_scores, answers_label=args.answers_label)
    if args.check:
        if not output.exists():
            print(f"Skill task matrix is missing: {output}")
            return 1
        if output.read_text(encoding="utf-8") != markdown:
            print(f"Skill task matrix is stale: {output}")
            return 1
        print(f"Skill task matrix is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    print(f"Wrote {output}")
    return 0


def render_report(task_paths: list[Path], answer_scores: list[dict[str, Any]] | None = None, *, answers_label: str = "reference") -> str:
    rubrics = [_load_rubric(path / "rubric.json") for path in task_paths]
    answer_scores = answer_scores or []
    lines = [
        "# TradeArena Skill Task Matrix",
        "",
        "This file is generated by `python scripts/score_skill_task_report.py`.",
        "The suite evaluates LLMs and coding agents as financial-audit agents,",
        "not as stock pickers or live trading assistants.",
        "",
        "TradeArena skills help agents inspect, reproduce, audit, and extend benchmark artifacts.",
        "They are not trading strategies, investment advice, broker integrations, or live execution tools.",
        "If a benchmarked model uses a skill, the skill must be recorded as part of the model, prompt, or retrieval configuration.",
        "",
        "## Capability Coverage",
        "",
        "| Ability | Task count | Measurable task | Scoring mode |",
        "| --- | ---: | --- | --- |",
    ]
    for ability, label in ABILITY_LABELS.items():
        matching = [rubric for rubric in rubrics if rubric["ability"] == ability]
        lines.append(
            f"| {label} | {len(matching)} | {_ability_task(ability)} | {_ability_scoring(ability)} |"
        )

    lines.extend(
        [
            "",
            "## Task Matrix",
            "",
            "| Task | Skill | Ability | Metric | Criteria | Pass threshold | Hard-fail terms |",
            "| --- | --- | --- | --- | ---: | ---: | --- |",
        ]
    )
    for rubric in rubrics:
        hard_fail_terms = ", ".join(rubric.get("hard_fail_terms", [])) or "default safety terms"
        lines.append(
            f"| `{rubric['task_id']}` | `{rubric['skill']}` | "
            f"{ABILITY_LABELS[rubric['ability']]} | {_escape(rubric['metric'])} | "
            f"{len(rubric['criteria'])} | {rubric['pass_threshold']} | {_escape(hard_fail_terms)} |"
        )

    if answer_scores:
        passed = sum(1 for row in answer_scores if row["passed"])
        score = sum(int(row["score"]) for row in answer_scores)
        max_score = sum(int(row["max_score"]) for row in answer_scores)
        lines.extend(
            [
                "",
                f"## {answers_label.title()} Answer Scorecard",
                "",
                f"Summary: {passed}/{len(answer_scores)} tasks passed; {score}/{max_score} rubric points earned.",
                "",
                "| Task | Ability | Score | Threshold | Passed | Hard fail |",
                "| --- | --- | ---: | ---: | --- | --- |",
            ]
        )
        for row in answer_scores:
            lines.append(
                f"| `{row['task_id']}` | {ABILITY_LABELS[row['ability']]} | "
                f"{row['score']}/{row['max_score']} | {row['pass_threshold']} | "
                f"{_bool_icon(bool(row['passed']))} | {_bool_icon(bool(row['hard_failed']))} |"
            )

    lines.extend(
        [
            "",
            "## Validation",
            "",
            "```bash",
            "python scripts/validate_skill_contract.py skills",
            "python scripts/score_skill_task.py --tasks-dir examples/skill_tasks --validate-only",
            "python scripts/score_skill_task.py --tasks-dir examples/skill_tasks --answers-dir examples/skill_task_answers/reference",
            "python scripts/score_skill_task_report.py --tasks-dir examples/skill_tasks --output docs/results/skill_task_matrix.md --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _load_rubric(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def score_answers(task_paths: list[Path], answers_dir: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for task_path in task_paths:
        answer_path = answers_dir / f"{task_path.name}.md"
        if not answer_path.exists():
            continue
        rows.append(score_task(task_path, answer_path.read_text(encoding="utf-8")).to_dict())
    return rows


def _ability_task(ability: str) -> str:
    return {
        "audit_accuracy": "Find trajectory risk edits, rejected orders, and partial fills",
        "risk_understanding": "Check risk-report completeness and missed controls",
        "execution_boundary_awareness": "Avoid stress-simulator transaction-cost overclaims",
        "claim_discipline": "Classify engineering, benchmark, and scientific claims",
        "reproduction_awareness": "Report commit, hash, commands, artifacts, and data-source flags",
        "plugin_engineering": "Propose a narrow plugin with deterministic tests",
    }[ability]


def _ability_scoring(ability: str) -> str:
    return {
        "audit_accuracy": "rubric match",
        "risk_understanding": "checklist score",
        "execution_boundary_awareness": "hard fail on boundary overclaim",
        "claim_discipline": "label accuracy",
        "reproduction_awareness": "field coverage",
        "plugin_engineering": "test and review checklist",
    }[ability]


def _escape(value: str) -> str:
    return value.replace("|", "\\|")


def _bool_icon(value: bool) -> str:
    return "yes" if value else "no"


if __name__ == "__main__":
    raise SystemExit(main())
